// Nested model for Pasien
class PasienNested {
  final int? id;
  final String? nama;
  final String? nomorRm;

  PasienNested({this.id, this.nama, this.nomorRm});

  factory PasienNested.fromJson(Map<String, dynamic> json) {
    return PasienNested(
      id: json['id'],
      nama: json['nama'],
      nomorRm: json['nomor_rm'] ?? json['nomorRm'],
    );
  }
}

// Nested model for Poli
class PoliNested {
  final int? id;
  final String? namaPoli;

  PoliNested({this.id, this.namaPoli});

  factory PoliNested.fromJson(Map<String, dynamic> json) {
    return PoliNested(
      id: json['id'],
      namaPoli: json['nama_poli'] ?? json['namaPoli'] ?? json['nama'],
    );
  }
}

// Nested model for Dokter
class DokterNested {
  final int? id;
  final String? nama;

  DokterNested({this.id, this.nama});

  factory DokterNested.fromJson(Map<String, dynamic> json) {
    return DokterNested(
      id: json['id'],
      nama: json['nama'],
    );
  }
}

class AntrianModel {
  final int? id;
  final String ticketNumber;
  final String status;
  final int pasienId;
  final int poliId;
  final int? dokterId;
  final String? keluhan;
  final DateTime? scheduledAt;
  final DateTime? createdAt;
  
  // Nested objects
  final PasienNested? pasien;
  final PoliNested? poli;
  final DokterNested? dokter;

  AntrianModel({
    this.id,
    this.ticketNumber = '', // Optional, generated by server
    required this.status,
    required this.pasienId,
    required this.poliId,
    this.dokterId,
    this.keluhan,
    this.scheduledAt,
    this.createdAt,
    this.pasien,
    this.poli,
    this.dokter,
  });

  // Getters for backward compatibility
  String? get namaPasien => pasien?.nama;
  String? get namaPoli => poli?.namaPoli;
  String? get namaDokter => dokter?.nama;

  factory AntrianModel.fromJson(Map<String, dynamic> json) {
    return AntrianModel(
      id: json['id'],
      ticketNumber: json['ticket_number'] ?? '',
      status: json['status'] ?? '',
      pasienId: json['pasien_id'] ?? json['pasienId'] ?? 0,
      poliId: json['poli_id'] ?? json['poliId'] ?? 0,
      dokterId: json['dokter_id'] ?? json['dokterId'],
      keluhan: json['keluhan'],
      scheduledAt: json['scheduled_at'] != null
          ? DateTime.tryParse(json['scheduled_at'])
          : null,
      createdAt: json['created_at'] != null
          ? DateTime.tryParse(json['created_at'])
          : null,
      pasien: json['pasien'] != null && json['pasien'] is Map
          ? PasienNested.fromJson(json['pasien'] as Map<String, dynamic>)
          : null,
      poli: json['poli'] != null && json['poli'] is Map
          ? PoliNested.fromJson(json['poli'] as Map<String, dynamic>)
          : null,
      dokter: json['dokter'] != null && json['dokter'] is Map
          ? DokterNested.fromJson(json['dokter'] as Map<String, dynamic>)
          : null,
    );
  }

  // Convert model to JSON for API requests
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      'ticket_number': ticketNumber,
      'status': status,
      'pasienId': pasienId,
      'poliId': poliId,
      if (dokterId != null) 'dokterId': dokterId,
      if (keluhan != null) 'keluhan': keluhan,
      if (scheduledAt != null) 'scheduled_at': scheduledAt!.toIso8601String(),
    };
  }
}
