class Pasien {
  final int? id;
  final String nomorRm;
  final String nik; // Added NIK field
  final String nama;
  final String tanggalLahir;
  final String nomorTelepon;
  final String alamat;
  final String? email;
  final String? password;

  Pasien({
    this.id,
    required this.nomorRm,
    required this.nik,
    required this.nama,
    required this.tanggalLahir,
    required this.nomorTelepon,
    required this.alamat,
    this.email,
    this.password,
  });

  factory Pasien.fromJson(Map<String, dynamic> json) {
    return Pasien(
      id: json['id'],
      // Backend uses snake_case keys
      nomorRm: json['nomor_rm'] ?? '',
      nik: json['nik'] ?? '',
      nama: json['nama'] ?? '',
      tanggalLahir: json['tanggal_lahir'] ?? '',
      nomorTelepon: json['nomor_telepon'] ?? '',
      alamat: json['alamat'] ?? '',
      email: json['email'] ?? null,
      password: json['password'] ?? null,
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{
      'nik': nik,
      'nama': nama,
      'tanggal_lahir': tanggalLahir,
      'nomor_telepon': nomorTelepon,
      'alamat': alamat,
    };
    // nomor_rm will be auto-generated by backend, don't send it
    if (email != null) map['email'] = email;
    if (password != null) map['password'] = password;
    if (id != null) map['id'] = id;
    return map;
  }
}
